#!/bin/bash
export TAXPLAN_API_MYSQL_HOST="127.0.0.1"
export TAXPLAN_API_MYSQL_PORT=8889
export TAXPLAN_API_MYSQL_USER="root"
export TAXPLAN_API_MYSQL_PASSWORD="root"
export TAXPLAN_API_MYSQL_DATABASE="taxplan"
export TAXPLAN_API_ADMIN_EMAIL="email@email.com"
export TAXPLAN_API_SESSION_SECRET=process.env.SESSION_SECRET
export TAXPLAN_API_STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY
export TAXPLAN_API_STRIPE_PUBLIC_KEY=process.env.STRIPE_PUBLIC_KEY
export TAXPLAN_API_POSTAGEAPP_API_KEY=process.env.POSTAGEAPP_API_KEY
export TAXPLAN_API_ROOT="/"
